namespace boo
{
const char* UDevButtonNames[] =
{
    "Button 0",
    "Button 1",
    "Button 2",
    "Button 3",
    "Button 4",
    "Button 5",
    "Button 6",
    "Button 7",
    "Button 8",
    "Button 9",
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    "Left",
    "Right",
    "Middle",
    "Side",
    "Extra",
    "Forward",
    "Back",
    "Task",
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    "Trigger",
    "Thumb",
    "Thumb2",
    "Top",
    "Top2",
    "Pinkie",
    "Base",
    "Base2",
    "Base3",
    "Base4",
    "Base5",
    "Base6",
    nullptr,
    nullptr,
    nullptr,
    "Dead",
    "A",
    "B",
    "C",
    "X",
    "Y",
    "Z",
    "TL",
    "TR",
    "TL2",
    "TR2",
    "Select",
    "Start",
    "Mode",
    "ThumbL",
    "ThumbR",
    nullptr,
    "Pen",
    "Rubber",
    "Brush",
    "Pencil",
    "Airbrush",
    "Finger",
    "Mouse",
    "Lens",
    "Quinttap",
    nullptr,
    "Touch",
    "Stylus",
    "Stylus2",
    "Doubletap",
    "Tripletap",
    "Quadtap",
    "Gear Down",
    "Gear Up",
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    "OK",
    "Select",
    "Goto",
    "Clear",
    "Power2",
    "Option",
    "Info",
    "Time",
    "Vendor",
    "Archive",
    "Program",
    "Channel",
    "Favorites",
    "EPG",
    "PVR",
    "MHP",
    "Language",
    "Title",
    "Subtitle",
    "Angle",
    "Zoom",
    "Mode",
    "Keyboard",
    "Screen",
    "PC",
    "TV",
    "TV2",
    "VCR",
    "VCR2",
    "SAT",
    "SAT2",
    "CD",
    "Tape",
    "Radio",
    "Tuner",
    "Player",
    "Text",
    "DVD",
    "AUX",
    "MP3",
    "Audio",
    "Video",
    "Directory",
    "List",
    "Memo",
    "Calendar",
    "Red",
    "Green",
    "Yellow",
    "Blue",
    "Channel Up",
    "Channel Down",
    "First",
    "Last",
    "AB",
    "Next",
    "Restart",
    "Slow",
    "Shuffle",
    "Break",
    "Previous",
    "Digits",
    "Teen",
    "Twenty",
    "Videophone",
    "Games",
    "Zoom In",
    "Zoom Out",
    "Zoom Reset",
    "Word Processor",
    "Editor",
    "Spreadsheet",
    "Graphics Editor",
    "Presentation",
    "Database",
    "News",
    "Voicemail",
    "Address Book",
    "Messenger",
    "Display Toggle",
    "Spellcheck",
    "Logoff",
    "Dollar",
    "Euro",
    "Frame Back",
    "Frame Forward",
    "Context Menu",
    "Media Repeat",
    "10 Channels Up",
    "10 Channels Down",
    "Images",
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    "Delete EOL",
    "Delete EOS",
    "Insert Line",
    "Delete Line",
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    "Fn",
    "ESC",
    "F1",
    "F2",
    "F3",
    "F4",
    "F5",
    "F6",
    "F7",
    "F8",
    "F9",
    "F10",
    "F11",
    "F12",
    "Fn 1",
    "Fn 2",
    "Fn D",
    "Fn E",
    "Fn F",
    "Fn S",
    "Fn B",
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    "Dot1",
    "Dot2",
    "Dot3",
    "Dot4",
    "Dot5",
    "Dot6",
    "Dot7",
    "Dot8",
    "Dot9",
    "Dot10",
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    "Num 0",
    "Num 1",
    "Num 2",
    "Num 3",
    "Num 4",
    "Num 5",
    "Num 6",
    "Num 7",
    "Num 8",
    "Num 9",
    "Num Star",
    "Num Pound",
    "Num A",
    "Num B",
    "Num C",
    "Num D",
    "Camera Focus",
    "WPS Button",
    "Touchpad Toggle",
    "Touchpad On",
    "Touchpad Off",
    "Camera Zoom In",
    "Camera Zoom Out",
    "Camera Up",
    "Camera Down",
    "Camera Left",
    "Camera Right",
    "Attendant On",
    "Attendant Off",
    "Attendant Toggle",
    "Lights Loggle",
    nullptr,
    "D-Pad Up",
    "D-Pad Down",
    "D-Pad Left",
    "D-Pad Right",
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    "ALS Toggle",
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    "Button Config",
    "Task Manager",
    "Journal",
    "Control Panel",
    "App Select",
    "Screen Saver",
    "Voice Command",
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    "Brightness Min",
    "Brightness Max",
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    "Kbd Input Assistant Prev",
    "Kbd Input Assistant Next",
    "Kbd Input Assistant Prev Group",
    "Kbd Input Assistant Next Group",
    "Kbd Input Assistant Accept",
    "Kbd Input Assistant Cancel",
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    "Trigger Happy 1",
    "Trigger Happy 2",
    "Trigger Happy 3",
    "Trigger Happy 4",
    "Trigger Happy 5",
    "Trigger Happy 6",
    "Trigger Happy 7",
    "Trigger Happy 8",
    "Trigger Happy 9",
    "Trigger Happy 10",
    "Trigger Happy 11",
    "Trigger Happy 12",
    "Trigger Happy 13",
    "Trigger Happy 14",
    "Trigger Happy 15",
    "Trigger Happy 16",
    "Trigger Happy 17",
    "Trigger Happy 18",
    "Trigger Happy 19",
    "Trigger Happy 20",
    "Trigger Happy 21",
    "Trigger Happy 22",
    "Trigger Happy 23",
    "Trigger Happy 24",
    "Trigger Happy 25",
    "Trigger Happy 26",
    "Trigger Happy 27",
    "Trigger Happy 28",
    "Trigger Happy 29",
    "Trigger Happy 30",
    "Trigger Happy 31",
    "Trigger Happy 32",
    "Trigger Happy 33",
    "Trigger Happy 34",
    "Trigger Happy 35",
    "Trigger Happy 36",
    "Trigger Happy 37",
    "Trigger Happy 38",
    "Trigger Happy 39",
    "Trigger Happy 40",
};
const char* UDevAxisNames[] =
{
    "X",
    "Y",
    "Z",
    "Rx",
    "Ry",
    "Rz",
    "Throttle",
    "Rudder",
    "Wheel",
    "Gas",
    "Brake",
    "Hat0X",
    "Hat0Y",
    "Hat1X",
    "Hat1Y",
    "Hat2X",
    "Hat2Y",
    "Hat3X",
    "Hat3Y",
    "Pressure",
    "Distance",
    "Tilt X",
    "Tilt Y",
    "Tool Width"
};
}
